# Generated by Django 4.2.11 on 2024-06-22 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeQuiz',
            fields=[
                ('title', models.CharField(max_length=20, unique=True)),
                ('no_of_questions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marks_per_question', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_choices', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('question_number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.CharField(max_length=100, unique=True)),
                ('timer_seconds', models.IntegerField(default=10)),
                ('correct_option', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(default='user1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.IntegerField()),
                ('quiz_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.makequiz')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.userdetails')),
            ],
            options={
                'unique_together': {('quiz_title', 'username')},
            },
        ),
        migrations.CreateModel(
            name='TakeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('selected_choice', models.IntegerField()),
                ('marks_per_question', models.PositiveIntegerField(default=2)),
                ('marks_alloted', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.makequiz')),
            ],
            options={
                'unique_together': {('quiz', 'question_number')},
            },
        ),
    ]
